spring:
  application:
    name: kboot-https-demo-client

logging:
  level:
#    root: warn
    ch.keepcalm.demo: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd E HH:mm:ss.SSS}){blue} - %clr(${spring.application.name:-}){green} - %clr(%-40.40logger{0}){magenta} - %clr(%m){green}%n"

# Management
management:
  endpoints:
    web:
      exposure:
        include: "*"

api:
  endpoint: "https://localhost:8081"
