apiVersion: apps/v1
kind: Deployment
metadata:
  name: https-demo-client
spec:
  template:
    spec:
      containers:
        - name: https-demo-client
          livenessProbe:
            httpGet:
              path: /actuator/info
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 3
            timeoutSeconds: 5
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            httpGet:
              path: /actuator/health
              port: 8080
